{% set name = "pydantic-config" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 417357b651aa6b33a59708b9daa75089aff1af765b231a164ac0791805f10507

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools
    - pip
  run:
    - python >=3.8
    - pydantic-settings >=2.0.1

test:
  imports:
    - pydantic_config
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jordantshaw/pydantic-config
  summary: Support for pydantic-settings configuration file loading
  license: MIT
  license_file: LICENSE
  doc_url: https://github.com/jordantshaw/pydantic-config
  dev_url: https://github.com/jordantshaw/pydantic-config

extra:
  recipe-maintainers:
    - jordantshaw
